- name: Set Install version variable
  when: font_nerd_version == 'latest'
  block:
    - name: Set Github API request header
      ansible.builtin.set_fact:
        github_api_request_headers:
          Accept: application/vnd.github+json
    - name: Merge Github API Authorization request header
      ansible.builtin.set_fact:
        github_api_request_headers: "{{ github_api_request_headers | combine(merge_reauest_header) }}"
      vars:
        merge_reauest_header:
          Authorization: Bearer {{ lookup('env', 'GITHUB_TOKEN') }}
      when: lookup('env', 'GITHUB_TOKEN') | length > 0
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ font_nerd_repo }}/releases/latest
        headers: "{{ github_api_request_headers }}"
      register: latest_releases
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_nerd_version: "{{ latest_releases.json.tag_name }}"
- name: Include Nerd font install task
  ansible.builtin.include_tasks:
    file: tasks/font/Nerd/install.yml
  loop: "{{ font_nerd_variations }}"
  loop_control:
    loop_var: variation
    label: "{{ variation }}"
